export const SEARCHFORJIFF = 'SEARCHFORJIFF';
export const JIFFSEARCHSUCCESS = 'JIFFSEARCHSUCCESS';
export const JIFFNOTHINGTOSEARCH = 'JIFFNOTHINGTOSEARCH';
export const JIFFNORESULTS= 'JIFFNORESULTS';
export const XCHANGESUCCESS= 'XCHANGESUCCESS';
export const XCHANGEFAILURE= 'XCHANGEFAILURE';
export const XCHANGEBASES = 'XCHANGEBASES';
